function setRFConfiguration(obj)

message = [typecast(cast(MessageType.SetRFConfig, 'uint8'),'uint8'), ...
    typecast(cast(obj.m_fLoFrequency, 'single'),'uint8'), ...
    typecast(cast(obj.m_fHiFrequency, 'single'),'uint8'), ...
    typecast(cast(obj.m_uDirection, 'uint8'),'uint8'), ...
    typecast(cast(obj.m_fTXPower, 'single'),'uint8')];

obj.sendMessage(message);
obj.waitForStatus;
